- name: Install MySQL server and client
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - mysql-common
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Change root user password on first run or when mysql.current_root_password was overrided with -e option
  mysql_user:
    login_user=root
    login_password={{ mysql.current_root_password }}
    name=root
    password={{ mysql.root_password }}
    priv=*.*:ALL,GRANT
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: Copy MySQL settings file
  template:
    src=my.cnf.j2
    dest=/etc/mysql/conf.d/my.cnf
    owner=root
    group=root
    mode=0644
  sudo: yes
  notify: mysql-restart

# Secure installation
- name: MySQL | Ensure python mysql is installed
  apt: pkg=python-mysqldb state=installed force=yes

- name: MySQL | Remove empty password users
  mysql_user: name='' password='' host=localhost priv=*.*:USAGE state=absent login_user=root login_password={{ mysql.root_password }}

- name: MySQL | Remove empty password users
  mysql_user: name='' password='' host=$ansible_fqdn priv=*.*:USAGE state=absent login_user=root login_password={{ mysql.root_password }}

- name: MySQL | Remove the MySQL test database
  mysql_db: db=test state=absent login_user=root login_password={{ mysql.root_password }}


- name: (Re)Create databases
  mysql_db:
    login_user=root
    login_password={{ mysql.root_password }}
    name={{ item }}
    state=present
  with_items: mysql.databases

- name: (Re)Create database users
  mysql_user:
    login_user=root
    login_password={{ mysql.root_password }}
    name={{ item.key }}
    password={{ item.value.password }}
    priv={{ item.value.priv }}
    state={{ item.value.state | default('present') }}
  with_dict: mysql.users
